# Generated by Django 5.1.4 on 2024-12-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_course', '0002_alter_review_course_alter_review_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_course.student'),
            preserve_default=False,
        ),
    ]
