# Generated by Django 5.1.4 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_course', '0003_alter_user_data_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
