# Generated by Django 5.1.4 on 2024-12-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_course', '0004_alter_teacher_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='headline',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
